### ISSUE TITLE
Lucida Sans Typewriter isn't installed by default on MacOS

### ISSUE THREAD

**Issue by nosami** [migueldeicaza/XtermSharp#25]
Maybe use Menlo or Monaco or Andale Mono instead as the default.

This is how it looks without the font installed - not sure which font is being used here.

<img width="636" alt="image" src="https://user-images.githubusercontent.com/667194/68859530-5d3d6600-06df-11ea-9ece-8140622aa361.png">

**Comment by migueldeicaza** [comment]
Defaulted to Courier, as it comes with all four faces.
