### ISSUE TITLE
XtermSharp as a Console Terminal?

### ISSUE THREAD

**Issue by gerardog** [migueldeicaza/XtermSharp#34]
Can I use XtermSharp to render a VT stream to the console? Kind of doing a Putty but inside the windows console. I looked at the source a little bit and it lacks a Console driver, which I could find in the Gui.cs repo, but I am not completely sure how it works... Does it just copy the whole XtermSharp buffer frame to the Console on each input? 

What approach would you recommend?

**Comment by migueldeicaza** [comment]
XtermSharp is the emulator - it needs a host of some sort.

You can write one if you want using Console.   I wrote one for the Gui.cs library framework that you could draw inspiration from
